routes/web.php
<?php

/*
|--------------------------------------------------------------------------
//AoUl$I1
| Web Routes 
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', 'Admin\LoginController@index')->name('/');
Route::post('login', 'Admin\LoginController@login')->name('login');
Route::get('forget-password', 'Admin\PasswordController@forgetPasswordIndex')->name('forget-password');
Route::post('forget-password', 'Admin\PasswordController@forgetPassword')->name('forget-password');

#auth
Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => ['auth']], function () {
	Route::post('logout', 'LoginController@logout')->name('logout');

	Route::get('home', 'HomeController@index')->name('home');

	Route::resource('users', 'UserController');
	Route::post('users/status/{id}', 'UserController@changeStatus')->name('users.status');

	Route::resource('positions', 'PositionController');
	
	Route::post('positions/active/{id}', 'PositionController@changeStatus')->name('positions.active');

	Route::post('change-password', 'PasswordController@changePassword')->name('change-password');

	Route::resource('timbers', 'TimberWebController');
	Route::post('timber/search', 'TimberWebController@searchTimber')->name('timber.search');

	Route::resource('locations', 'AdminLocationController');
	Route::get('location/list', 'AdminLocationController@getLocation')->name('locations.list');

	Route::resource('location-map', 'LocationMapController');
	Route::resource('printlogs', 'PrintlogsController');

	Route::post('import-csv','TimberWebController@importCSVFile')->name('import-csv');
	
});

app/Http/Controllers/Admin/PositionController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\model\position\Position;
use App\User;
use Validator;
use Symfony\Component\HttpFoundation\Response;
use Yajra\DataTables\Facades\DataTables;



class PositionController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {

        $positions = Position::orderBy('id', 'desc')->get();
        return view('position.index', compact('positions'));

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('position.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'name' => 'required'
        ]);

        if ($validator->fails()) {
            return response()->json([
                'success' => false,
                'message' => $validator->getMessageBag(),
            ], 422);
        }

        $obj = new Position;
        $obj->name = $request->name;
        $obj->save();
        
        return response()->json([
            'success' => true,
            'message' => 'Position Created Successfully.',
        ], 200);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $position = Position::find($id);
        return view('position.edit', compact('position'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $ids)
    {
        $validator = Validator::make($request->all(), [
            'name' => 'required',
            'active' => 'required'
        ]);

        if ($validator->fails()) {
            return response()->json([
                'success' => false,
                'message' => $validator->getMessageBag(),
            ], 422);
        }
        $obj = Position::find($request->id);
        $obj->name = $request->name;
        $obj->active = $request->active;
        $obj->save();
       
        return response()->json([
            'success' => true,
            'message' => 'Position Updated Successfully.',
        ], 200);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $user = User::where('position', $id)->get();
        if ($user->count() > 0){

            return response()->json([
                'success' => false,
                'message' => 'Position is asigned to a user. Does not allow to delete position',
            ], 404);

        } else {
           
            Position::where('id', $id)->delete();
        }
    }

    public function changeStatus(Request $request, $id)
    {
        $position = Position::find($id);

        if ($position->active == 1) {
            $position->active = 0;
        } else {
            $position->active = 1;
        }
        $position->save();

        return response()->json([
            'success' => true,
            'message' => 'Status updated successfully'
        ], 200);
    }
}

app/Http/Controllers/Api/PositionController.php
<?php 

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\User;
use Exception;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Auth;
use Carbon\Carbon;
use Validator;

class PositionController extends Controller 
{

  /**
   * Display a listing of the resource.
   *
   * @return Response
   */
  public function index()
  {
    
  }

  /**
   * Show the form for creating a new resource.
   *
   * @return Response
   */
  public function create()
  {
    
  }

  /**
   * Store a newly created resource in storage.
   *
   * @return Response
   */
  public function store(Request $request)
  {
    
  }

  /**
   * Display the specified resource.
   *
   * @param  int  $id
   * @return Response
   */
  public function show($id)
  {
    
  }

  /**
   * Show the form for editing the specified resource.
   *
   * @param  int  $id
   * @return Response
   */
  public function edit($id)
  {
    
  }

  /**
   * Update the specified resource in storage.
   *
   * @param  int  $id
   * @return Response
   */
  public function update($id)
  {
    
  }

  /**
   * Remove the specified resource from storage.
   *
   * @param  int  $id
   * @return Response
   */
  public function destroy($id)
  {
    
  }
  
}

?>

resources/views/position/edit.blade.php
@extends('layouts.layout')
@section('content')
<div class="row">
    <div class="col-lg-12">
        <div class="card">
            <div class="card-body">
                <div class=""> <h4 class="card-title">Edit Position</h4></div>
                <br>
                    <div class="alert alert-danger position-edit-error col-lg-8" role="alert" style="display:none;">
                        <p class="mesg-error"></p>
                    </div>
                <form>
                    <div class="form-group">
                        <label for="name" class="form-label text-dark">Position</label>
                        <input type="text" id="name" name="name" class="form-control col-lg-8" value="{{$position->name}}" placeholder="Position Name" required>
                    </div>

                    <div class="form-group">
                    <label for="active" class="form-label text-dark">Status</label>

                    <select name="active" id="active" class="form-control col-lg-8" required>
                        <option value="">Select</option>
                        <option value="1" {{ $position->active == 1 ? 'selected' : '' }}>Active</option>
                        <option value="0" {{ $position->active == 0 ? 'selected' : '' }}>Inactive</option>
                    </select>
                    </div>
                    
                    <a href="javascript:void(0)" class="btn btn-info float-left" data-id="{{$position->id}}" id="editUser">{{ trans('global.update') }}</a>&nbsp;
                    <a href="{{ route('admin.positions.index') }}" style="border: 1px solid #808890;" class="btn btn-outline-default">Cancel</a>
                </form>
            </div>
        </div>
    </div>
</div>
@endsection
@section('scripts')
<script>
    $(document).ready(function(){

        $('#editUser').click(function(e){
            e.preventDefault();
            $.ajaxSetup({
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                }
            });

            var name = $('#name').val();
            var active = $('#active').val();            
            var id = $(this).data("id");

            $.ajax({
                url:"{{ route("admin.positions.update",[0]) }}",
                type: 'PUT',
                data: { id: id, name: name, active: active },
                success: function(response){
                    
                    if (response.success) {
                        alert('Position Updated Successfully')
                        window.location.href = '{{ route('admin.positions.index') }}'
                    }
                },

                error: function(response){
                    if (response.status == 422){
                        $('.position-edit-error').show(0).delay(3000).hide(400);
                        setTimeout(function() { 
                            $('.position-edit-error').fadeOut(); 
                        }, 3000);
                        $('.mesg-error').html(response.responseJSON.message.active);
                        $('.mesg-error').html(response.responseJSON.message.name);
                    }
                }
            });
        });
    });

</script>
@endsection

resources/views/position/index.blade.php
@extends('layouts.layout')
@section('content')
<div class="row">
    <div class="col-lg-12">
        <div class="card">
            <div class="card-body">
                <div class=""><h4 class="card-title">Add Position</h4></div>
                <br>
                <div class="alert alert-danger position-error col-lg-8" role="alert" style="display:none;">
                    <p class="mesg-error"></p>
                </div>
                <form>
                    <div class="form-group">
                    <label for="name" class="form-label text-dark">Position</label>
                    <input type="text" id="name" name="name" class="form-control col-lg-8" placeholder="Position Name" required>
                    <span class="name-span"></span>
                    </div>
                    <a href="javascript:void(0)" class="btn btn-info" id="storeUser">{{ trans('global.save') }}</a>
                </form>
          
            <table id="position_table" class="table-responsive table table-bordered table-striped table-hover">
                <thead class="bg-color">
                    <tr>
                        <th>Position</th>
                        <th>Status</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($positions as $position)
                    <tr>
                        <td>{{$position->name}}</td>

                        @if ($position->active == 1)
                        <td><a class="positionStatus btn btn-success btn-xs" data-id="{{$position->id}}" href="javascript:void(0)">Active</a></td>
                        @else
                        <td><a class="positionStatus btn btn-danger btn-xs" data-id="{{$position->id}}" href="javascript:void(0)">Inactive</a></td>
                        @endif
                        <td>
                            <a href="{{ route('admin.positions.edit', [$position->id]) }}" class="btn btn-info btn-xs"><i class="fa fa-pencil"></i> Edit</a>

                            <a class="btn btn-danger deleteRecord btn-xs" data-id="{{$position->id}}" href="javascript:void(0)" method='delete'><i class="fa fa-trash"></i> Delete</a>

                        </td>
                    </tr>
                    @endforeach
                </tbody>
            </table>

            </div>
        </div>
    </div>
</div>
<style type="text/css">
    .name {
        border: 1px solid red;
    }
    .col-sm-12.col-md-6 {
        margin-bottom: -20px;
    }
</style>
@endsection
@section('scripts')
<script>
    $(document).ready(function(){
        $('#position_table').DataTable({
            'columnDefs': [{
                'targets': [2],
                'orderable': false
            }],
            'sPaginationType': 'full_numbers'
            
        });

        // $('input#name').keydown(function(){
        //     $('#name').removeClass('name');
        //     $('span.name-span').empty();
        // });

        $('#storeUser').click(function(e){
            e.preventDefault();
            $.ajaxSetup({
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                }
            });

            var name = $('#name').val();
           
            $.ajax({
                url: "{{ route('admin.positions.store') }}",
                method: 'post',
                data: { name: name },

                success: function(response){
                    if (response.success) {
                        alert('Position added successfully')
                        location.reload()
                    }
                },

                error: function(response){
                    if (response.status == 422){
                        $('.position-error').show(0).delay(3000).hide(400);
                        setTimeout(function() { 
                            $('.position-error').fadeOut(); 
                        }, 3000);
                        $('.mesg-error').html(response.responseJSON.message.name);
                        // $('#name').addClass('name');
                        // $('.name-span').text(response.responseJSON.message.name).css({'color':'red'});
                    }
                }
            });
        });

        $(document).on('click','.deleteRecord', function(){
            $.ajaxSetup({
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                }
            });

            var id = $(this).data("id");

            if (confirm('Are you sure to Delete?')) {
                $.ajax({
                    url: "positions/"+id,
                    type: 'DELETE',
                    data: {
                        "id": id,
                    },
                    
                    success: function (response){
                        location.reload();
                    },
                    error: function(response){
                        if (response.status == 404){
                            $('.position-error').show(0).delay(3000).hide(400);
                            setTimeout(function() { 
                                $('.position-error').fadeOut(); 
                            }, 3000);
                            $('.mesg-error').html(response.responseJSON.message);
                     }
                 }

             });
            }

        })


        $(document).on('click','.positionStatus', function(){
            $.ajaxSetup({
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                }
            });
            var id = $(this).data("id");

            if (confirm('Are you sure to change status?')) {
                $.ajax({
                    url: "positions/active/"+id,
                    type: 'post',
                    data: {
                            "id": id
                        },
                    success: function (response){
                        location.reload();
                    }
                });
            }
        });
      
    });

</script>
@endsection