routes/web.php
<?php

/*
|--------------------------------------------------------------------------
//AoUl$I1
| Web Routes 
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', 'Admin\LoginController@index')->name('/');
Route::post('login', 'Admin\LoginController@login')->name('login');
Route::get('forget-password', 'Admin\PasswordController@forgetPasswordIndex')->name('forget-password');
Route::post('forget-password', 'Admin\PasswordController@forgetPassword')->name('forget-password');

#auth
Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => ['auth']], function () {
	Route::post('logout', 'LoginController@logout')->name('logout');

	Route::get('home', 'HomeController@index')->name('home');

	Route::resource('users', 'UserController');
	Route::post('users/status/{id}', 'UserController@changeStatus')->name('users.status');

	Route::resource('positions', 'PositionController');
	
	Route::post('positions/active/{id}', 'PositionController@changeStatus')->name('positions.active');

	Route::post('change-password', 'PasswordController@changePassword')->name('change-password');

	Route::resource('timbers', 'TimberWebController');
	Route::post('timber/search', 'TimberWebController@searchTimber')->name('timber.search');

	Route::resource('locations', 'AdminLocationController');
	Route::get('location/list', 'AdminLocationController@getLocation')->name('locations.list');

	Route::resource('location-map', 'LocationMapController');
	Route::resource('printlogs', 'PrintlogsController');

	Route::post('import-csv','TimberWebController@importCSVFile')->name('import-csv');
	
});

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Passport\HasApiTokens;
use Illuminate\Database\Eloquent\SoftDeletes;


class User extends Authenticatable
{
    use SoftDeletes, HasApiTokens, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'first_name',
        'last_name',
        'position', 
        'email', 
        'password',
        'account_type'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 
        'remember_token'
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime'
    ];


    public function positions()
    {
        return $this->belongsTo('App\model\position\Position', 'position', 'id');
    }
}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Http\Controllers\Api\AuthController;
use Exception;
use App\model\position\Position;
use App\User;
use App\Notifications\PushNotification;
use URL;


class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = User::where('account_type', 1)->orderBy('id', 'desc')->get();
        return view('user.index', compact('users'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $positions = Position::where('active',1)->orderBy('name', 'asc')->get();
        return view('user.create', compact('positions'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        try {
            $request["account_type"]=1;
            $auth_obj = new AuthController;
            $register = $auth_obj->register($request);
            
            return response(['success'=>true, 'message'=>"User successfully registered ","errors"=>(object)array()],201);
        }
        catch(\Illuminate\Database\QueryException  $e){
            return response(['message'=>"Something went wrong","errors"=>array("exception"=>["Bad Request"])],400);
        }
        catch(\Illuminate\Http\Exceptions\HttpResponseException $e){
            return response(['message'=>"Something went wrong","errors"=>array("exception"=>["Bad Request"])],400);
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        User::where('id', $id)->delete();
        return response(['success'=>true, 'message'=>"User deleted successfully ","errors"=>(object)array()],201);  
    }

    public function changeStatus(Request $request, $id)
    {
        $user = User::where('id', $id)->where('account_type', 1)->first();

        if ($user->status == 1) {
            $user->status = 0;

            $FCMTokens = [];
            $PushNotification = "";
            $pushnotificationsData = [];

            $FCMTokens['Android'][]=$user->device_token;
            $pushnotificationsData['to'] = $FCMTokens;
            $pushnotificationsData['notification'] = array(
                'title' => 'USER DEACTIVATION ALERT',
                'text' => '',
                'click_action' => '',
                'body'=>'User has been deactivated.',
                'picture_url'=>URL::asset('images/block-user.png')
            );
            $pushnotificationsData['data'] = [
                "type"=>"USERDEACTIVATIONALERT",
                'title' => 'USER DEACTIVATION ALERT',
                'text' => '',
                'click_action' => '',
                'body'=>'User has been deactivated.',
                'picture_url'=>URL::asset('images/block-user.png')
            ];
            
            $PushNotification=PushNotification::PushNotifications($pushnotificationsData);

        } else {
            $user->status = 1;
        }
        $user->save();

        return response()->json([
            'success' => true,
            'message' => 'Status updated successfully'
        ], 200);
    }

}

resources/views/user/create.blade.php
@extends('layouts.layout')
@section('content')
<div class="row">
    <div class="col-lg-12">
        <div class="card">
            <div class="card-body">
                <div class=""> <h4 class="card-title">Add User</h4></div>
                    <br>
                    <div class="alert alert-danger user-error col-lg-8" role="alert" style="display:none">
                        <p class="mesg-error" style="color: red;"></p>
                    </div>

                <form id="validateForm">
                    <div class="form-group">
                    <label for="first_name" class="form-label text-dark">First Name</label>
                    <input type="text" id="first_name" name="first_name" class="form-control col-lg-8" placeholder="First name" required>
                    </div>

                    <div class="form-group">
                    <label for="last_name" class="form-label text-dark">Last Name</label>
                    <input type="text" id="last_name" name="last_name" class="form-control col-lg-8" placeholder="Last name" required>
                    </div>

                    <div class="form-group">
                    <label for="email" class="form-label text-dark">Email</label>
                    <input type="email" id="email" name="email" class="form-control col-lg-8" placeholder="Email" required>
                    </div>

                    <div class="form-group">
                    <label for="position" class="form-label text-dark">Position</label>

                    <select name="position" id="position" class="form-control col-lg-8" required>
                        <option value="">Select</option>
                        @foreach($positions as $position)
                            <option value="{{$position->id}}" >{{ $position->name }}</option>
                        @endforeach
                    </select>
                    </div>
                    
                    <a href="javascript:void(0)" class="btn btn-info float-left save_button" id="storeUser">{{ trans('global.save') }}</a>
                    <button class="btn btn-info float-left" style="display: none;" id="load_button">Saving <i class='fa fa-circle-o-notch fa-spin'></i></button>&nbsp;
                    <a href="{{ route('admin.users.index') }}" style="border: 1px solid #808890;" class="btn btn-outline-default">Cancel</a>
                   
                </form>

            </div>
        </div>
    </div>
</div>

@endsection
@section('scripts')
<script>
    $(document).ready(function(){

        $('#storeUser').click(function(e){
            e.preventDefault();
            $.ajaxSetup({
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                }
            });

            var first_name = $('#first_name').val();
            var last_name = $('#last_name').val();
            var email = $('#email').val();
            var position = $('#position').val();
            $('.save_button').css({display:'none'});
            $('#load_button').css({display:'block'});
            $.ajax({
                url: "{{ route('admin.users.store') }}",
                method: 'post',
                data: { first_name: first_name, last_name: last_name, email: email, position: position },

                success: function(response){
                    $('#load_button').css({display:'none'});
                    $('.save_button').css({display:'block'});
                    if (response.success) {
                        alert('User created successfully')
                        window.location.href = '{{ route('admin.users.index') }}'
                    }
                },

                error: function(response){
                    $('#load_button').css({display:'none'});
                    $('.save_button').css({display:'block'});
                    if (response.status == 422){
                        $('.user-error').show(0).delay(5000).hide(400);
                        setTimeout(function() { 
                            $('.user-error').fadeOut(); 
                        }, 5000);
                        $('.mesg-error').html(response.responseJSON.errors.position);
                        $('.mesg-error').html(response.responseJSON.errors.email[0]);
                        $('.mesg-error').html(response.responseJSON.errors.email[1]);
                        $('.mesg-error').html(response.responseJSON.errors.last_name);
                        $('.mesg-error').html(response.responseJSON.errors.first_name);
                    }
                    if (response.status == 500){
                        $('.user-error').show(0).delay(3000).hide(400);
                        setTimeout(function() { 
                            $('.user-error').fadeOut(); 
                        }, 3000);
                        $('.mesg-error').text('Internal server error');
                    }
                }
            });
        });
    });

</script>
@endsection

resources/views/user/index.blade.php
@extends('layouts.layout')
@section('content')
<div class="row">
    <div class="col-lg-12">
        <div class="card">
            <div class="card-body">

                <div class="card-title"> <h4>User List</h4></div><br>
                
                <table id="user_table" class="table-responsive table table-bordered table-striped table-hover">
                    <thead class="bg-color">
                        <tr>
                            <th>Fist Name</th>
                            <th>Last Name</th>
                            <th>Email</th>
                            <th>Position</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($users as $user)
                        <tr>
                            <td>{{$user->first_name}}</td>
                            <td>{{$user->last_name}}</td>
                            <td>{{$user->email}}</td>
                            <td>{{$user->positions->name}}</td>
                            <td>
                                @if ($user->status == 1)
                                    <a class="blockRecord btn btn-success btn-xs" data-id="{{$user->id}}" href="javascript:void(0)">Unblock</a>
                                @else
                                    <a class="blockRecord btn btn-danger btn-xs" data-id="{{$user->id}}" href="javascript:void(0)">Block</a>
                                @endif

                               {{--  <a class="deleteRecord fa fa-trash" data-id="{{$user->id}}" href="#" data-toggle="tooltip" data-placement="top" title="Delete" method='delete'></a> --}}

                            </td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
<style type="text/css">
    .toolbar {
    float: left;
}
</style>

@endsection
@section('scripts')
<script>
    $(document).ready(function(){
        $('#user_table').DataTable({
            'columnDefs': [{
                'targets': [4],
                'orderable': false
            }],
            'dom': 'l<"toolbar">frtip',
            'initComplete': function(){
                $("div.toolbar").html('<a class = "btn btn-sm btn-info" href="{{ route('admin.users.create') }}"><i class="fa fa-plus"></i> Add User</a>');
            },
            "sPaginationType": "full_numbers"
        });

    //.....User Delete..........................................................
        // $(document).on('click','.deleteRecord', function(){
        //     $.ajaxSetup({
        //         headers: {
        //             'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
        //         }
        //     });
        //     var id = $(this).data("id");
        //    // var token = $("meta[name='csrf-token']").attr("content");

        //     if (confirm('Are you sure to Delete?')) {
        //         $.ajax({
        //             url: "users/"+id,
        //             type: 'DELETE',
        //             data: {
        //                 "id": id,
        //                 //"_token": token,
        //             },
        //             success: function (response){
        //                 location.reload();
        //                 // if (response.success) {
        //                 //     $('.alert-success').show();
        //                 //     $('.mesg-success').html(response.message);
        //                 // }
        //             }
        //         });
        //     }
        // });
    //........End Delete..........................................................

        $(document).on('click','.blockRecord', function(){
            $.ajaxSetup({
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                }
            });
            var id = $(this).data("id");

            if (confirm('Are you sure to change status?')) {
                $.ajax({
                    url: "users/status/"+id,
                    type: 'post',
                    data: {
                            "id": id
                        },
                    success: function (response){
                        location.reload();
                    }
                });
            }
        });

    });
</script>
@endsection