routes/web.php
<?php

/*
|--------------------------------------------------------------------------
//AoUl$I1
| Web Routes 
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', 'Admin\LoginController@index')->name('/');
Route::post('login', 'Admin\LoginController@login')->name('login');
Route::get('forget-password', 'Admin\PasswordController@forgetPasswordIndex')->name('forget-password');
Route::post('forget-password', 'Admin\PasswordController@forgetPassword')->name('forget-password');

#auth
Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => ['auth']], function () {
	Route::post('logout', 'LoginController@logout')->name('logout');

	Route::get('home', 'HomeController@index')->name('home');

	Route::resource('users', 'UserController');
	Route::post('users/status/{id}', 'UserController@changeStatus')->name('users.status');

	Route::resource('positions', 'PositionController');
	
	Route::post('positions/active/{id}', 'PositionController@changeStatus')->name('positions.active');

	Route::post('change-password', 'PasswordController@changePassword')->name('change-password');

	Route::resource('timbers', 'TimberWebController');
	Route::post('timber/search', 'TimberWebController@searchTimber')->name('timber.search');

	Route::resource('locations', 'AdminLocationController');
	Route::get('location/list', 'AdminLocationController@getLocation')->name('locations.list');

	Route::resource('location-map', 'LocationMapController');
	Route::resource('printlogs', 'PrintlogsController');

	Route::post('import-csv','TimberWebController@importCSVFile')->name('import-csv');
	
});

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <title>{{ trans('panel.site_title') }}</title>
    <link href="https://unpkg.com/@coreui/coreui/dist/css/coreui.min.css" rel="stylesheet" />
    <link href="{{ asset('css/custom.css') }}" rel="stylesheet" />

    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
</head>

<body class="header-fixed sidebar-fixed aside-menu-fixed aside-menu-hidden login-page">
    <div class="app flex-row align-items-center">
        <div class="container">
            
            @yield("content")
            
        </div>
    </div>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>

            @yield('scripts')

</body>

</html>

resources/views/layouts/layout.blade.php
<!DOCTYPE html>
<html lang="en">

    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="csrf-token" content="{{ csrf_token() }}">

        <title>{{ trans('panel.site_title') }}</title>
{{-- Start template css --}}
        <!-- Standard -->
        <link rel="shortcut icon" href="http://placehold.it/64.png/000/fff">
        <!-- Retina iPad Touch Icon-->
        <link rel="apple-touch-icon" sizes="144x144" href="http://placehold.it/144.png/000/fff">
        <!-- Retina iPhone Touch Icon-->
        <link rel="apple-touch-icon" sizes="114x114" href="http://placehold.it/114.png/000/fff">
        <!-- Standard iPad Touch Icon-->
        <link rel="apple-touch-icon" sizes="72x72" href="http://placehold.it/72.png/000/fff">
        <!-- Standard iPhone Touch Icon-->
        <link rel="apple-touch-icon" sizes="57x57" href="http://placehold.it/57.png/000/fff">

        <!-- Styles -->
        <link href="{{ asset('assets/css/lib/weather-icons.css') }}" rel="stylesheet" />
        <link href="{{ asset('assets/css/lib/owl.carousel.min.css') }}" rel="stylesheet" />
        <link href="{{ asset('assets/css/lib/owl.theme.default.min.css') }}" rel="stylesheet" />
        <link href="{{ asset('assets/css/lib/font-awesome.min.css') }}" rel="stylesheet">
        <link href="{{ asset('assets/css/lib/themify-icons.css') }}" rel="stylesheet">
        <link href="{{ asset('assets/css/lib/menubar/sidebar.css') }}" rel="stylesheet">
        <link href="{{ asset('assets/css/lib/bootstrap.min.css') }}" rel="stylesheet">

        <link href="{{ asset('assets/css/lib/helper.css') }}" rel="stylesheet">
        <link href="{{ asset('assets/css/style.css') }}" rel="stylesheet">
        <link href="{{ asset('css/custom.css') }}" rel="stylesheet" />

{{-- End template css --}}
{{-- <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"> --}}


    {{-- <link rel="stylesheet" href="https://cdn.datatables.net/1.10.12/css/dataTables.bootstrap.min.css" /> --}}
{{-- <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.css" rel="stylesheet"/> --}}
    {{-- start --}}
    {{-- <link href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css" rel="stylesheet" /> --}}
    <link href="https://cdn.datatables.net/1.10.20/css/dataTables.bootstrap4.min.css" rel="stylesheet" />
    {{-- end --}}
    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.5/css/select2.min.css" rel="stylesheet" />    
    </head>

    <body>
      
        @include('layouts.sidebar')

        @include('layouts.header')


        <div class="content-wrap">
            <div class="main">
                <div class="container-fluid">
                   
                @yield('content')
                   
                </div>
            </div>
            <footer class="footer">
                <div class="container-fluid">
                  <div class="row text-xs-center">
                    <div class="col-sm-4 text-sm-left mb-0-5 mb-sm-0">
                        <p>
                        True North &copy; <script>document.write(new Date().getFullYear())</script>
                        </p>
                    </div>
                  </div>
                </div>
            </footer>
        </div>


    <!-- jquery vendor -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.8/js/select2.min.js" defer></script>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>

    {{-- ggg --}}
    <script src="https://code.jquery.com/jquery-3.3.1.js"></script>
    <script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.20/js/dataTables.bootstrap4.min.js"></script>
    {{-- ggg --}}

{{-- Start template js --}}
        {{-- <script src="{{ asset('assets/js/lib/jquery.min.js') }}"></script> --}}
        <script src="{{ asset('assets/js/lib/jquery.nanoscroller.min.js') }}"></script>
        <!-- nano scroller -->
        <script src="{{ asset('assets/js/lib/menubar/sidebar.js') }}"></script>
        <script src="{{ asset('assets/js/lib/preloader/pace.min.js') }}"></script>
        <!-- sidebar -->
        <script src="{{ asset('assets/js/lib/bootstrap.min.js') }}"></script>

        <!-- bootstrap -->
        <script src="{{ asset('assets/js/lib/circle-progress/circle-progress.min.js') }}"></script>
        {{-- <script src="{{ asset('assets/js/lib/circle-progress/circle-progress-init.js') }}"></script> --}}

        {{-- <script src="{{ asset('assets/js/lib/morris-chart/raphael-min.js') }}"></script> --}}


        {{-- <script src="{{ asset('assets/js/lib/morris-chart/morris.js') }}"></script> --}}
        {{-- <script src="{{ asset('assets/js/lib/morris-chart/morris-init.js') }}"></script> --}}

        <!--  flot-chart js -->
        {{-- <script src="{{ asset('assets/js/lib/flot-chart/jquery.flot.js') }}"></script> --}}
        {{-- <script src="{{ asset('assets/js/lib/flot-chart/jquery.flot.resize.js') }}"></script> --}}
        {{-- <script src="{{ asset('assets/js/lib/flot-chart/flot-chart-init.js') }}"></script> --}}
        <!-- // flot-chart js -->


        {{-- <script src="{{ asset('assets/js/lib/vector-map/jquery.vmap.js') }}"></script> --}}
        <!-- scripit init-->
        {{-- <script src="{{ asset('assets/js/lib/vector-map/jquery.vmap.min.js') }}"></script> --}}
        <!-- scripit init-->

        <script src="{{ asset('assets/js/lib/vector-map/jquery.vmap.sampledata.js') }}"></script>

        <!-- scripit init-->
        {{-- <script src="{{ asset('assets/js/lib/vector-map/country/jquery.vmap.world.js') }}"></script> --}}
        <!-- scripit init-->
        {{-- <script src="{{ asset('assets/js/lib/vector-map/country/jquery.vmap.algeria.js') }}"></script> --}}
        <!-- scripit init-->
        {{-- <script src="{{ asset('assets/js/lib/vector-map/country/jquery.vmap.argentina.js') }}"></script> --}}
        <!-- scripit init-->
        {{-- <script src="{{ asset('assets/js/lib/vector-map/country/jquery.vmap.brazil.js') }}"></script> --}}
        <!-- scripit init-->
        {{-- <script src="{{ asset('assets/js/lib/vector-map/country/jquery.vmap.france.js') }}"></script> --}}
        <!-- scripit init-->
        {{-- <script src="{{ asset('assets/js/lib/vector-map/country/jquery.vmap.germany.js') }}"></script> --}}
        <!-- scripit init-->
        {{-- <script src="{{ asset('assets/js/lib/vector-map/country/jquery.vmap.greece.js') }}"></script> --}}
        <!-- scripit init-->
        {{-- <script src="{{ asset('assets/js/lib/vector-map/country/jquery.vmap.iran.js') }}"></script> --}}
        <!-- scripit init-->
        {{-- <script src="{{ asset('assets/js/lib/vector-map/country/jquery.vmap.iraq.js') }}"></script> --}}
        <!-- scripit init-->
        {{-- <script src="{{ asset('assets/js/lib/vector-map/country/jquery.vmap.russia.js') }}"></script> --}}
        <!-- scripit init-->
        {{-- <script src="{{ asset('assets/js/lib/vector-map/country/jquery.vmap.tunisia.js') }}"></script> --}}
        <!-- scripit init-->
        {{-- <script src="{{ asset('assets/js/lib/vector-map/country/jquery.vmap.europe.js') }}"></script> --}}
        <!-- scripit init-->
        {{-- <script src="{{ asset('assets/js/lib/vector-map/country/jquery.vmap.usa.js') }}"></script> --}}
        <!-- scripit init-->
        {{-- <script src="{{ asset('assets/js/lib/vector-map/vector.init.js') }}"></script> --}}

        {{-- <script src="{{ asset('assets/js/lib/weather/jquery.simpleWeather.min.js') }}"></script> --}}
        {{-- <script src="{{ asset('assets/js/lib/weather/weather-init.js') }}"></script> --}}
        {{-- <script src="{{ asset('assets/js/lib/owl-carousel/owl.carousel.min.js') }}"></script> --}}
        {{-- <script src="{{ asset('assets/js/lib/owl-carousel/owl.carousel-init.js') }}"></script> --}}
        <script src="{{ asset('assets/js/scripts.js') }}"></script>
{{-- End template js --}}

        <script>
            $(document).ready(function(){
                $('.sidebar-toggle').click(function(){
                    if ($('.sidebar-toggle').hasClass('is-active')){
                        $('img').hide();
                        $('.logo').addClass('admin-logo');
                    } else {
                        $('img').show();
                        $('.logo').removeClass('admin-logo');
                    }
                });

                $("#myBtn").click(function(){
                    $("#exampleModalCenter").modal();
                });

                $('.change-password').click(function(){
                    $('.password-fields').show();
                    $(this).hide();
                });
                $('.cancel-change-password').click(function(){
                    $('.password-fields').hide();
                    $('.change-password').show();
                });

            //................Change Password For Admin...........................
                $('#storePassword').click(function(e){
                    e.preventDefault();
                    $.ajaxSetup({
                        headers: {
                            'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                        }
                    });

                    var new_password = $('#new_password').val();
                    var current_password = $('#current_password').val();
                    var confirm_new_password = $('#confirm_new_password').val();

                    $.ajax({
                        url: "{{ route('admin.change-password') }}",
                        method: 'post',
                        data: { new_password: new_password, current_password: current_password, confirm_new_password: confirm_new_password },

                        success: function(response){
                            console.log(response)
                            if (response.success) {
                                $('.success').show();
                                $('.password-success').html(response.message);
                            }
                        },

                        error: function(response){
                            console.log(response)

                            if (response.status == 422){
                                $('.danger').show(0).delay(3000).hide(400);
                                setTimeout(function() { 
                                    $('.danger').fadeOut(); 
                                }, 3000);
                                $('.password-error').html(response.responseJSON.errors.confirm_new_password);
                                $('.password-error').html(response.responseJSON.errors.new_password);
                                $('.password-error').html(response.responseJSON.errors.current_password);
                            }
                            if (response.status == 404){
                                $('.danger').show(0).delay(3000).hide(400);
                                setTimeout(function() { 
                                    $('.danger').fadeOut(); 
                                }, 3000);
                                $('.password-error').html(response.responseJSON.message);
                            }
                            if (response.status == 500){
                                $('.danger').show(0).delay(3000).hide(400);
                                setTimeout(function() { 
                                    $('.danger').fadeOut(); 
                                }, 3000);
                                $('.password-error').text('Internal server error');
                            }
                        }
                    });
                });
            //....................................................................
          });
        </script>

            @yield('scripts')
    </body>

</html>

resources/views/layouts/sidebar.blade.php
  <div class="sidebar sidebar-hide-to-small sidebar-shrink sidebar-gestures" style="height: 100%; position: fixed;">
            <div class="nano">
                <div class="nano-content">
                     <div class="logo"><img src="{{ asset('images/Logo.png') }}" alt=""/></div>
                        
                    <ul>
                        <li class="{{ request()->is('admin/home') || request()->is('admin/home/*') ? 'active' : '' }}">
                        <a href="{{ route('admin.home') }}"><i class="ti-home"></i> Dashboard </a>   
                        </li>

                        <li class="{{ request()->is('admin/users') || request()->is('admin/users/*') ? 'active' : '' }}">
                            <a href="{{ route('admin.users.index') }}" ><i class="ti-user"></i> User </a>
                        </li>

                        <li class="{{ request()->is('admin/positions') || request()->is('admin/positions/*') ? 'active' : '' }}">
                            <a href="{{ route('admin.positions.index') }}"><i class="ti-layout"></i> Position </a>
                        </li>

                        <li class="{{ request()->is('admin/timbers') || request()->is('admin/timbers/*') ? 'active' : '' }}">
                        <a href="{{ route('admin.timbers.index') }}"><i class="ti-view-list-alt"></i>Timber</a>
                        </li>

                        <li class="{{ request()->is('admin/location-map') || request()->is('admin/location-map/*') ? 'active' : '' }}">
                            <a href="{{ route('admin.location-map.index') }}"><i class="ti-layout"></i> Location map </a>
                        </li>

                        <li class="{{ request()->is('admin/printlogs') || request()->is('admin/printlogs/*') ? 'active' : '' }}">
                        <a href="{{ route('admin.printlogs.index') }}"><i class="ti-view-list-alt"></i>Print logs</a>
                        </li>
                    

                        {{-- <li><a href="app-event-calender.html"><i class="ti-calendar"></i> Calender </a></li>

                        <li class="label">Apps</li>
                        <li><a class="sidebar-sub-toggle"><i class="ti-bar-chart-alt"></i>  Charts  <span class="sidebar-collapse-icon ti-angle-down"></span></a>
                            <ul>
                                <li><a href="chart-flot.html">Flot</a></li>
                                <li><a href="chart-morris.html">Morris</a></li>
                                <li><a href="chartjs.html">Chartjs</a></li>
                                <li><a href="chartist.html">Chartist</a></li>
                                <li><a href="chart-peity.html">Peity</a></li>
                                <li><a href="chart-sparkline.html">Sparkle</a></li>
                                <li><a href="chart-knob.html">Knob</a></li>
                            </ul>
                        </li>

                        <li><a href="app-email.html"><i class="ti-email"></i> Email</a></li>
                        <li><a href="app-profile.html"><i class="ti-user"></i> Profile</a></li>
                        <li><a href="app-widget-card.html"><i class="ti-layout-grid2-alt"></i> Widget</a></li>
                        <li class="label">Features</li>
                        <li><a class="sidebar-sub-toggle"><i class="ti-layout"></i> UI Elements <span class="sidebar-collapse-icon ti-angle-down"></span></a>
                            <ul>
                                <li><a href="ui-typography.html">Typography</a></li>
                                <li><a href="ui-alerts.html">Alerts</a></li>

                                <li><a href="ui-button.html">Button</a></li>
                                <li><a href="ui-dropdown.html">Dropdown</a></li>

                                <li><a href="ui-list-group.html">List Group</a></li>

                                <li><a href="ui-progressbar.html">Progressbar</a></li>
                                <li><a href="ui-tab.html">Tab</a></li>

                            </ul>
                        </li>
                        <li><a class="sidebar-sub-toggle"><i class="ti-panel"></i> Components <span class="sidebar-collapse-icon ti-angle-down"></span></a>
                            <ul>
                                <li><a href="uc-calendar.html">Calendar</a></li>
                                <li><a href="uc-carousel.html">Carousel</a></li>
                                <li><a href="uc-weather.html">Weather</a></li>
                                <li><a href="uc-datamap.html">Datamap</a></li>
                                <li><a href="uc-todo-list.html">To do</a></li>
                                <li><a href="uc-scrollable.html">Scrollable</a></li>
                                <li><a href="uc-sweetalert.html">Sweet Alert</a></li>
                                <li><a href="uc-toastr.html">Toastr</a></li>
                                <li><a href="uc-range-slider-basic.html">Basic Range Slider</a></li>
                                <li><a href="uc-range-slider-advance.html">Advance Range Slider</a></li>
                                <li><a href="uc-nestable.html">Nestable</a></li>

                                <li><a href="uc-rating-bar-rating.html">Bar Rating</a></li>
                                <li><a href="uc-rating-jRate.html">jRate</a></li>
                            </ul>
                        </li>
                        <li><a class="sidebar-sub-toggle"><i class="ti-layout-grid4-alt"></i> Table <span class="sidebar-collapse-icon ti-angle-down"></span></a>
                            <ul>
                                <li><a href="table-basic.html">Basic</a></li>

                                <li><a href="table-export.html">Datatable Export</a></li>
                                <li><a href="table-row-select.html">Datatable Row Select</a></li>
                                <li><a href="table-jsgrid.html">Editable </a></li>
                            </ul>
                        </li>
                        <li><a class="sidebar-sub-toggle"><i class="ti-heart"></i> Icons <span class="sidebar-collapse-icon ti-angle-down"></span></a>
                            <ul>
                                <li><a href="font-themify.html">Themify</a></li>
                            </ul>
                        </li>
                        <li><a class="sidebar-sub-toggle"><i class="ti-map"></i> Maps <span class="sidebar-collapse-icon ti-angle-down"></span></a>
                            <ul>
                                <li><a href="gmaps.html">Basic</a></li>
                                <li><a href="vector-map.html">Vector Map</a></li>
                            </ul>
                        </li>
                        <li class="label">Form</li>
                        <li class="label">Extra</li>
                        <li><a class="sidebar-sub-toggle"><i class="ti-files"></i> Invoice <span class="sidebar-collapse-icon ti-angle-down"></span></a>
                            <ul>
                                <li><a href="invoice.html">Basic</a></li>
                                <li><a href="invoice-editable.html">Editable</a></li>
                            </ul>
                        </li>
                        <li><a class="sidebar-sub-toggle"><i class="ti-target"></i> Pages <span class="sidebar-collapse-icon ti-angle-down"></span></a>
                            <ul>
                                <li><a href="page-login.html">Login</a></li>
                                <li><a href="page-register.html">Register</a></li>
                                <li><a href="page-reset-password.html">Forgot password</a></li>
                            </ul>
                        </li>
                        <li><a href="../documentation/index.html"><i class="ti-file"></i> Documentation</a></li> 

                        <li>
                            <a href="{{ route('admin.logout') }}" onclick="event.preventDefault(); document.getElementById('frm-logout').submit();">
                                <i class="ti-close"></i>
                                Logout
                            </a>
                            <form id="frm-logout" action="{{ route('admin.logout') }}" method="POST" style="display: none;">
                                {{ csrf_field() }}
                            </form>

                        </li>  --}}
                    </ul>
                </div>
            </div>
        </div>
        <!-- /# sidebar -->